# Generated by Django 5.1.2 on 2024-11-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_entry_category_entry_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='content',
            field=models.TextField(default='No content available.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(default='Untitled Entry', max_length=200),
        ),
    ]
